package icecaptools;

/* Methods annotated with this attribute will get the signature 
 * specified in 'signature'. This can be used to program interrupt
 * handlers, since they sometimes are required to have a specific name
 * 
 * Alternative explanation:
 * 
 *   Giving a Java method this attribute will make sure that it gets
 *   compiled into C, just like when using the IcecapCompileMe attribute.
 *   Additionally it will be given the name specified in "signature" and
 *   not the default autogenerated name.
 *   
 *   As an example of use see: test.AVR.ATMega2560.TimerTest
 */
public @interface IcecapCFunc {
    String signature() default "";
    String requiredIncludes() default "";
    String hasReturnValue() default "false";
}
