package devices;

public interface TargetConfiguration {

	/* The folder into which the C source has been generated */
	String getOutputFolder();
	
	/* The command(s) required to build the C source to produce an
	 * executable for the target.
	 * 
	 * The command to invoke the C compiler must be the element in the array. 
	 * It should only contain target specific filenames. Files generated by the
	 * icecap tool are added automatically.
	 * 
	 */
	String[] getBuildCommands();
	
	/* Return a command to apply after compilation. Return null if none applies 
	 * */
	String getPostBuildCommand();
	
	/* Returns the command for deploying the generated executable to the target.
	 * 
	 * Use the $EXE$ to refer to the executable name. 
	 */
	String getDeployCommand();
	
	/* Return the number of bytes that should be allocated for the
	 * Java heap at runtime.
	 */
	int getJavaHeapSize();
}
